FROM node:18 as build

WORKDIR /usr/src/app/frontend
COPY frontend .
# create env file if it doesn't exist
RUN touch tasking-manager.env
COPY example.env tasking-manager.en[v] ../

## SETUP
RUN yarn

# need to list all environment variables here or Digital Ocean won't insert them  
ARG TM_APP_BASE_URL
ARG TM_APP_API_URL
ARG TM_APP_API_VERSION
ARG TM_ORG_NAME
ARG TM_ORG_CODE
ARG TM_ORG_URL
ARG TM_ORG_LOGO
ARG TM_ORG_PRIVACY_POLICY_URL
ARG TM_ORG_TWITTER
ARG TM_ORG_FB
ARG TM_ORG_INSTAGRAM
ARG TM_ORG_YOUTUBE
ARG TM_ORG_GITHUB
ARG TM_DEFAULT_LOCALE
ARG TM_MAPPER_LEVEL_INTERMEDIATE
ARG TM_MAPPER_LEVEL_ADVANCED
ARG TM_MATOMO_ID
ARG TM_MATOMO_ENDPOINT
ARG TM_SERVICE_DESK
ARG TM_IMAGE_UPLOAD_API_URL
ARG TM_HOMEPAGE_VIDEO_URL
ARG TM_HOMEPAGE_IMG_HIGH
ARG TM_HOMEPAGE_IMG_LOW
ARG TM_MAPBOX_TOKEN
ARG TM_ENABLE_SERVICEWORKER
ARG TM_IMPORT_MAX_FILESIZE
ARG TM_MAX_AOI_AREA
ARG TM_USER_STATS_API_URL
ARG TM_HOMEPAGE_STATS_API_URL
ARG TM_CLIENT_ID
ARG TM_CLIENT_SECRET
ARG TM_REDIRECT_URI
ARG OSM_SERVER_URL
ARG TM_ORG_NAME
ARG OSM_REGISTER_URL
ARG ID_EDITOR_URL
ARG POTLATCH2_EDITOR_URL
ARG PDEDITOR_URL
ARG TM_SENTRY_FRONTEND_DSN
ARG TM_ENVIRONMENT
ARG TM_DEFAULT_CHANGESET_COMMENT
ARG RAPID_EDITOR_URL

ARG PD_CONSUMER_KEY
ARG PD_CONSUMER_SECRET
ARG PD_SERVER_URL

# SERVE
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /usr/src/app/frontend/build /usr/share/nginx/html
COPY --from=build /usr/src/app/frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
